---
- name: mdadm

  hosts: otus-vm2
  become: true

  roles:
    - role: ansible-mdadm
      vars:
        mdadm_arrays:
          - name: 'md0'
            devices:
              - '/dev/sdb'
              - '/dev/sdc'
              - '/dev/sdd'
              - '/dev/sde'
            filesystem: 'ext4'
            level: '5'
            mountpoint: '/mnt/0/'
            state: '{{ array_state | default("present") }}'


...

